apply plugin: 'com.android.library'
apply from: '../shared/keepUnitySymbols.gradle'
apply from: '../shared/common.gradle'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:12
    implementation 'androidx.legacy:legacy-support-v4:1.0.0' // Assets/LevelPlay/Editor/ISInMobiAdapterDependencies.xml:16
    implementation 'androidx.lifecycle:lifecycle-process:2.6.2' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:17
    implementation 'androidx.recyclerview:recyclerview:1.2.1' // Assets/LevelPlay/Editor/ISMintegralAdapterDependencies.xml:15
    implementation 'com.android.installreferrer:installreferrer:2.1' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:7
    implementation 'com.applovin:applovin-sdk:13.6.4' // Assets/LevelPlay/Editor/ISAppLovinAdapterDependencies.xml:9
    implementation 'com.appsflyer:af-android-sdk:6.17.5' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:5
    implementation 'com.appsflyer:purchase-connector:2.2.0' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:8
    implementation 'com.appsflyer:unity-wrapper:6.17.81' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:6
    implementation 'com.bigossp:bigo-ads:6.0.0' // Assets/LevelPlay/Editor/ISBigoAdapterDependencies.xml:9
    implementation 'com.facebook.android:audience-network-sdk:6.22.0' // Assets/LevelPlay/Editor/ISFacebookAdapterDependencies.xml:5
    implementation 'com.fyber:marketplace-sdk:8.4.7' // Assets/LevelPlay/Editor/ISFyberAdapterDependencies.xml:5
    implementation 'com.google.android.gms:play-services-ads:25.3.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-ads-identifier:18.1.0' // Assets/LevelPlay/Editor/IronSourceSDKDependencies.xml:12
    implementation 'com.google.android.gms:play-services-base:18.10.0' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk:1.3.1' // Assets/LevelPlay/Editor/ISAdMobAdapterDependencies.xml:8
    implementation 'com.google.android.play:core-common:2.0.4' // Packages/com.google.play.core/Editor/Dependencies.xml:3
    implementation 'com.google.android.play:review:2.0.0' // Packages/com.google.play.review/Editor/Dependencies.xml:3
    implementation 'com.google.android.ump:user-messaging-platform:4.0.0' // Assets/GoogleMobileAds/Editor/GoogleUmpDependencies.xml:7
    implementation 'com.google.firebase:firebase-analytics:23.2.0' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:16
    implementation 'com.google.firebase:firebase-analytics-unity:13.15.0' // Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:21
    implementation 'com.google.firebase:firebase-app-unity:13.15.0' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:25
    implementation 'com.google.firebase:firebase-common:22.2.0' // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:16
    implementation 'com.google.firebase:firebase-config:23.1.0' // Packages/com.google.firebase.remote-config/Firebase/Editor/RemoteConfigDependencies.xml:16
    implementation 'com.google.firebase:firebase-config-unity:13.15.0' // Packages/com.google.firebase.remote-config/Firebase/Editor/RemoteConfigDependencies.xml:23
    implementation 'com.google.firebase:firebase-crashlytics-ndk:20.1.0' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:16
    implementation 'com.google.firebase:firebase-crashlytics-unity:13.15.0' // Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:23
    implementation 'com.inmobi.monetization:inmobi-ads-kotlin:11.4.1' // Assets/LevelPlay/Editor/ISInMobiAdapterDependencies.xml:9
    implementation 'com.mbridge.msdk.oversea:mbridge_android_sdk:16.9.91' // Assets/LevelPlay/Editor/ISMintegralAdapterDependencies.xml:8
    implementation 'com.my.target:mytarget-sdk:5.51.2' // Assets/LevelPlay/Editor/ISMyTargetAdapterDependencies.xml:9
    implementation 'com.pangle.global:pag-sdk:8.2.0.4' // Assets/LevelPlay/Editor/ISPangleAdapterDependencies.xml:12
    implementation 'com.unity3d.ads:unity-ads:4.20.0' // Assets/LevelPlay/Editor/ISUnityAdsAdapterDependencies.xml:9
    implementation 'com.unity3d.ads-mediation:admob-adapter:5.13.0' // Assets/LevelPlay/Editor/ISAdMobAdapterDependencies.xml:12
    implementation 'com.unity3d.ads-mediation:applovin-adapter:5.9.0' // Assets/LevelPlay/Editor/ISAppLovinAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:bidmachine-adapter:5.7.0' // Assets/LevelPlay/Editor/ISBidMachineAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:bigo-adapter:5.11.0' // Assets/LevelPlay/Editor/ISBigoAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:facebook-adapter:5.4.0' // Assets/LevelPlay/Editor/ISFacebookAdapterDependencies.xml:9
    implementation 'com.unity3d.ads-mediation:fyber-adapter:5.10.0' // Assets/LevelPlay/Editor/ISFyberAdapterDependencies.xml:9
    implementation 'com.unity3d.ads-mediation:inmobi-adapter:5.9.0' // Assets/LevelPlay/Editor/ISInMobiAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:mediation-sdk:9.6.0' // Assets/LevelPlay/Editor/IronSourceSDKDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:mintegral-adapter:5.18.0' // Assets/LevelPlay/Editor/ISMintegralAdapterDependencies.xml:19
    implementation 'com.unity3d.ads-mediation:mytarget-adapter:5.6.0' // Assets/LevelPlay/Editor/ISMyTargetAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:pangle-adapter:5.22.0' // Assets/LevelPlay/Editor/ISPangleAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:unityads-adapter:5.12.0' // Assets/LevelPlay/Editor/ISUnityAdsAdapterDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:vungle-adapter:5.13.0' // Assets/LevelPlay/Editor/ISVungleAdapterDependencies.xml:9
    implementation 'com.vungle:vungle-ads:7.7.7' // Assets/LevelPlay/Editor/ISVungleAdapterDependencies.xml:5
    implementation 'io.bidmachine:ads:3.7.1' // Assets/LevelPlay/Editor/ISBidMachineAdapterDependencies.xml:12
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packaging {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/armeabi-v7a/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    namespace "com.unity3d.player"
    ndkPath "**NDKPATH**"
    ndkVersion "**NDKVERSION**"
    compileSdk **APIVERSION**
    buildToolsVersion "**BUILDTOOLS**"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk **MINSDK**
        targetSdk **TARGETSDK**
        ndk {
            abiFilters **ABIFILTERS**
            debugSymbolLevel **DEBUGSYMBOLLEVEL**
        }
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
**DEFAULT_CONFIG_SETUP**
    }

    lint {
        abortOnError false
    }

    androidResources {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**
